### PR TITLE
Adding PUT method

### PR DESCRIPTION
**Pull request by zn3x**
In addition to PUT. There was some `server_id` that needed to be passed multiple times, So I changed calls to functions `send_ok()` in order not to take ownership of `server_id`.

For PUT, I didn't find any icecast client I knew that uses `chunked tranfer encoding` like in [this documentation](https://gist.github.com/ePirat/adc3b8ba00d85b7e3870)
This should now work using ffmpeg

### CODE REVIEW

**Review by BananaPuncher714 — COMMENTED** [review]
Looks good! Thanks for the contribution.

**Comment by BananaPuncher714** [comment]
There are some potential issues though, in hindsight.

Namely, if the source returns an invalid header, or if the server is unable to write any bytes to the stream, it may throw an error or return, and not remove itself from the map of sources. That's why sending the 200 OK for the source method was done before inserting the source into the map.

**Comment by zn3x** [comment]
@BananaPuncher714 That's why I did use `.ok()` when calling functions that will write to stream
like here:
`
source_stream(&mut stream, &source_timeout, &arc, queue_size, burst_size).await.ok();
`
It won't throw an error and return to `handle_connection()`
if it can't write to stream or connection problem it will remove source from map of sources.
But it should be tested if some invalid header is passed, a header with `Transfer-Encoding: chunked` or `Content-Length: len` will potentially be a problem if client is not an icecast client

**Comment by BananaPuncher714** [comment]
In some parts, such as if the source does not include the Expect header, or if there is a unicode decoding error, it returns Ok after sending a bad request response, from the function immediately without removing the source. Line 484 is an example.

**Comment by zn3x** [comment]
How about checking before adding to map of sources?
And only getting media from source after adding it to map

**Comment by BananaPuncher714** [comment]
Yes, that would be ideal. Proper verification and validation of headers and information is meant to be done before adding it to the server. Adding to the source map should only be done after everything is correct, and all that remains is to read the data. I would also send the 200 OK for the PUT request *after* the source has been removed from the map, but that's just my personal preference.

**Pull request merged**
